#ifndef __S3C64XX_GPIO_REGS_H__
#define __S3C64XX_GPIO_REGS_H__

#ifndef __ASSEMBLY__

#include "types.h"

/* 1 CON, 1 CONSLP */
typedef struct gpio_1c1s_bank {
    S3C64XX_REG32   con;
    S3C64XX_REG32   dat;
    S3C64XX_REG32   pud;
    S3C64XX_REG32   conslp;
    S3C64XX_REG32   pudslp;
    S3C64XX_REG32   dump[3];
}gpio_1c1s_bank_t, gpio_bank_t;

/* 2 CON, 1 CONSLP */
typedef struct gpio_2c1s_bank {
    S3C64XX_REG32   con0;
    S3C64XX_REG32   con1;
    S3C64XX_REG32   dat;
    S3C64XX_REG32   pud;
    S3C64XX_REG32   conslp;
    S3C64XX_REG32   pudslp;
    S3C64XX_REG32   dump[2];
}gpio_2c1s_bank_t;

/* 2 CON, 0 CONSLP */
typedef struct gpio_2c0s_bank {
    S3C64XX_REG32   con0;
    S3C64XX_REG32   con1;
    S3C64XX_REG32   dat;
    S3C64XX_REG32   pud;
}gpio_2c0s_bank_t;

/* 1 CON, 0 CONSLP */
typedef struct gpio_1c0s_bank {
    S3C64XX_REG32   con0;
    S3C64XX_REG32   dat;
    S3C64XX_REG32   pud;
    S3C64XX_REG32   dump;
}gpio_1c0s_bank_t;

/* I/O PORT (see manual chapter 9) */
typedef struct s3c64xx_gpio{
    gpio_1c1s_bank_t bank_AG[7];
    gpio_2c1s_bank_t bank_H[1];
    gpio_1c1s_bank_t bank_IJ[2];
    gpio_2c0s_bank_t bank_KL[2];
    gpio_1c0s_bank_t bank_MN[2];
    gpio_1c1s_bank_t bank_OQ[3];
} /*__attribute__((__packed__))*/ S3C64XX_GPIO;

#endif /* __ASSEMBLY__ */

/*
 * GPIO
 */
#define ELFIN_GPIO_BASE     0x7f008000

#define GPACON_OFFSET       0x00
#define GPADAT_OFFSET       0x04
#define GPAPUD_OFFSET       0x08
#define GPACONSLP_OFFSET    0x0C
#define GPAPUDSLP_OFFSET    0x10
#define GPBCON_OFFSET       0x20
#define GPBDAT_OFFSET       0x04
#define GPBPUD_OFFSET       0x08
#define GPBCONSLP_OFFSET    0x0C
#define GPBPUDSLP_OFFSET    0x30
#define GPCCON_OFFSET       0x40
#define GPCDAT_OFFSET       0x44
#define GPCPUD_OFFSET       0x48
#define GPCCONSLP_OFFSET    0x4C
#define GPCPUDSLP_OFFSET    0x50
#define GPDCON_OFFSET       0x60
#define GPDDAT_OFFSET       0x64
#define GPDPUD_OFFSET       0x68
#define GPDCONSLP_OFFSET    0x6C
#define GPDPUDSLP_OFFSET    0x70
#define GPECON_OFFSET       0x80
#define GPEDAT_OFFSET       0x84
#define GPEPUD_OFFSET       0x88
#define GPECONSLP_OFFSET    0x8C
#define GPEPUDSLP_OFFSET    0x90
#define GPFCON_OFFSET       0xA0
#define GPFDAT_OFFSET       0xA4
#define GPFPUD_OFFSET       0xA8
#define GPFCONSLP_OFFSET    0xAC
#define GPFPUDSLP_OFFSET    0xB0
#define GPGCON_OFFSET       0xC0
#define GPGDAT_OFFSET       0xC4
#define GPGPUD_OFFSET       0xC8
#define GPGCONSLP_OFFSET    0xCC
#define GPGPUDSLP_OFFSET    0xD0
#define GPHCON0_OFFSET      0xE0
#define GPHCON1_OFFSET      0xE4
#define GPHDAT_OFFSET       0xE8
#define GPHPUD_OFFSET       0xEC
#define GPHCONSLP_OFFSET    0xF0
#define GPHPUDSLP_OFFSET    0xF4
#define GPICON_OFFSET       0x100
#define GPIDAT_OFFSET       0x104
#define GPIPUD_OFFSET       0x108
#define GPICONSLP_OFFSET    0x10C
#define GPIPUDSLP_OFFSET    0x110
#define GPJCON_OFFSET       0x120
#define GPJDAT_OFFSET       0x124
#define GPJPUD_OFFSET       0x128
#define GPJCONSLP_OFFSET    0x12C
#define GPJPUDSLP_OFFSET    0x130
#define SPCON_OFFSET        0x1A0
#define MEM0DRVCON_OFFSET   0x1D0
#define MEM1DRVCON_OFFSET   0x1D4
#define GPKCON0_OFFSET      0x800
#define GPKCON1_OFFSET      0x804
#define GPKDAT_OFFSET       0x808
#define GPKPUD_OFFSET       0x80C
#define GPLCON0_OFFSET      0x810
#define GPLCON1_OFFSET      0x814
#define GPLDAT_OFFSET       0x818
#define GPLPUD_OFFSET       0x81C
#define GPMCON_OFFSET       0x820
#define GPMDAT_OFFSET       0x824
#define GPMPUD_OFFSET       0x828
#define GPNCON_OFFSET       0x830
#define GPNDAT_OFFSET       0x834
#define GPNPUD_OFFSET       0x838
#define GPOCON_OFFSET       0x140
#define GPODAT_OFFSET       0x144
#define GPOPUD_OFFSET       0x148
#define GPOCONSLP_OFFSET    0x14C
#define GPOPUDSLP_OFFSET    0x150
#define GPPCON_OFFSET       0x160
#define GPPDAT_OFFSET       0x164
#define GPPPUD_OFFSET       0x168
#define GPPCONSLP_OFFSET    0x16C
#define GPPPUDSLP_OFFSET    0x170
#define GPQCON_OFFSET       0x180
#define GPQDAT_OFFSET       0x184
#define GPQPUD_OFFSET       0x188
#define GPQCONSLP_OFFSET    0x18C
#define GPQPUDSLP_OFFSET    0x190

#define EINTPEND_OFFSET     0x924

#define GPACON_REG      __REG(ELFIN_GPIO_BASE+GPACON_OFFSET)
#define GPADAT_REG      __REG(ELFIN_GPIO_BASE+GPADAT_OFFSET)
#define GPAPUD_REG      __REG(ELFIN_GPIO_BASE+GPAPUD_OFFSET)
#define GPACONSLP_REG       __REG(ELFIN_GPIO_BASE+GPACONSLP_OFFSET)
#define GPAPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPAPUDSLP_OFFSET)
#define GPBCON_REG      __REG(ELFIN_GPIO_BASE+GPBCON_OFFSET)
#define GPBDAT_REG      __REG(ELFIN_GPIO_BASE+GPBDAT_OFFSET)
#define GPBPUD_REG      __REG(ELFIN_GPIO_BASE+GPBPUD_OFFSET)
#define GPBCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPBCONSLP_OFFSET)
#define GPBPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPBPUDSLP_OFFSET)
#define GPCCON_REG      __REG(ELFIN_GPIO_BASE+GPCCON_OFFSET)
#define GPCDAT_REG      __REG(ELFIN_GPIO_BASE+GPCDAT_OFFSET)
#define GPCPUD_REG      __REG(ELFIN_GPIO_BASE+GPCPUD_OFFSET)
#define GPCCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPCCONSLP_OFFSET)
#define GPCPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPCPUDSLP_OFFSET)
#define GPDCON_REG      __REG(ELFIN_GPIO_BASE+GPDCON_OFFSET)
#define GPDDAT_REG      __REG(ELFIN_GPIO_BASE+GPDDAT_OFFSET)
#define GPDPUD_REG      __REG(ELFIN_GPIO_BASE+GPDPUD_OFFSET)
#define GPDCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPDCONSLP_OFFSET)
#define GPDPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPDPUDSLP_OFFSET)
#define GPECON_REG      __REG(ELFIN_GPIO_BASE+GPECON_OFFSET)
#define GPEDAT_REG      __REG(ELFIN_GPIO_BASE+GPEDAT_OFFSET)
#define GPEPUD_REG      __REG(ELFIN_GPIO_BASE+GPEPUD_OFFSET)
#define GPECONSLP_REG       __REG(ELFIN_GPIO_BASE+GPECONSLP_OFFSET)
#define GPEPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPEPUDSLP_OFFSET)
#define GPFCON_REG      __REG(ELFIN_GPIO_BASE+GPFCON_OFFSET)
#define GPFDAT_REG      __REG(ELFIN_GPIO_BASE+GPFDAT_OFFSET)
#define GPFPUD_REG      __REG(ELFIN_GPIO_BASE+GPFPUD_OFFSET)
#define GPFCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPFCONSLP_OFFSET)
#define GPFPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPFPUDSLP_OFFSET)
#define GPGCON_REG      __REG(ELFIN_GPIO_BASE+GPGCON_OFFSET)
#define GPGDAT_REG      __REG(ELFIN_GPIO_BASE+GPGDAT_OFFSET)
#define GPGPUD_REG      __REG(ELFIN_GPIO_BASE+GPGPUD_OFFSET)
#define GPGCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPGCONSLP_OFFSET)
#define GPGPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPGPUDSLP_OFFSET)
#define GPHCON0_REG     __REG(ELFIN_GPIO_BASE+GPHCON0_OFFSET)
#define GPHCON1_REG     __REG(ELFIN_GPIO_BASE+GPHCON1_OFFSET)
#define GPHDAT_REG      __REG(ELFIN_GPIO_BASE+GPHDAT_OFFSET)
#define GPHPUD_REG      __REG(ELFIN_GPIO_BASE+GPHPUD_OFFSET)
#define GPHCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPHCONSLP_OFFSET)
#define GPHPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPHPUDSLP_OFFSET)
#define GPICON_REG      __REG(ELFIN_GPIO_BASE+GPICON_OFFSET)
#define GPIDAT_REG      __REG(ELFIN_GPIO_BASE+GPIDAT_OFFSET)
#define GPIPUD_REG      __REG(ELFIN_GPIO_BASE+GPIPUD_OFFSET)
#define GPICONSLP_REG       __REG(ELFIN_GPIO_BASE+GPICONSLP_OFFSET)
#define GPIPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPIPUDSLP_OFFSET)
#define GPJCON_REG      __REG(ELFIN_GPIO_BASE+GPJCON_OFFSET)
#define GPJDAT_REG      __REG(ELFIN_GPIO_BASE+GPJDAT_OFFSET)
#define GPJPUD_REG      __REG(ELFIN_GPIO_BASE+GPJPUD_OFFSET)
#define GPJCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPJCONSLP_OFFSET)
#define GPJPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPJPUDSLP_OFFSET)
#define GPKCON0_REG     __REG(ELFIN_GPIO_BASE+GPKCON0_OFFSET)
#define GPKCON1_REG     __REG(ELFIN_GPIO_BASE+GPKCON1_OFFSET)
#define GPKDAT_REG      __REG(ELFIN_GPIO_BASE+GPKDAT_OFFSET)
#define GPKPUD_REG      __REG(ELFIN_GPIO_BASE+GPKPUD_OFFSET)
#define GPLCON0_REG     __REG(ELFIN_GPIO_BASE+GPLCON0_OFFSET)
#define GPLCON1_REG     __REG(ELFIN_GPIO_BASE+GPLCON1_OFFSET)
#define GPLDAT_REG      __REG(ELFIN_GPIO_BASE+GPLDAT_OFFSET)
#define GPLPUD_REG      __REG(ELFIN_GPIO_BASE+GPLPUD_OFFSET)
#define GPMCON_REG      __REG(ELFIN_GPIO_BASE+GPMCON_OFFSET)
#define GPMDAT_REG      __REG(ELFIN_GPIO_BASE+GPMDAT_OFFSET)
#define GPMPUD_REG      __REG(ELFIN_GPIO_BASE+GPMPUD_OFFSET)
#define GPNCON_REG      __REG(ELFIN_GPIO_BASE+GPNCON_OFFSET)
#define GPNDAT_REG      __REG(ELFIN_GPIO_BASE+GPNDAT_OFFSET)
#define GPNPUD_REG      __REG(ELFIN_GPIO_BASE+GPNPUD_OFFSET)
#define GPOCON_REG      __REG(ELFIN_GPIO_BASE+GPOCON_OFFSET)
#define GPODAT_REG      __REG(ELFIN_GPIO_BASE+GPODAT_OFFSET)
#define GPOPUD_REG      __REG(ELFIN_GPIO_BASE+GPOPUD_OFFSET)
#define GPOCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPOCONSLP_OFFSET)
#define GPOPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPOPUDSLP_OFFSET)
#define GPPCON_REG      __REG(ELFIN_GPIO_BASE+GPPCON_OFFSET)
#define GPPDAT_REG      __REG(ELFIN_GPIO_BASE+GPPDAT_OFFSET)
#define GPPPUD_REG      __REG(ELFIN_GPIO_BASE+GPPPUD_OFFSET)
#define GPPCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPPCONSLP_OFFSET)
#define GPPPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPPPUDSLP_OFFSET)
#define GPQCON_REG      __REG(ELFIN_GPIO_BASE+GPQCON_OFFSET)
#define GPQDAT_REG      __REG(ELFIN_GPIO_BASE+GPQDAT_OFFSET)
#define GPQPUD_REG      __REG(ELFIN_GPIO_BASE+GPQPUD_OFFSET)
#define GPQCONSLP_REG       __REG(ELFIN_GPIO_BASE+GPQCONSLP_OFFSET)
#define GPQPUDSLP_REG       __REG(ELFIN_GPIO_BASE+GPQPUDSLP_OFFSET)

#define GPACON      (ELFIN_GPIO_BASE+GPACON_OFFSET)
#define GPADAT      (ELFIN_GPIO_BASE+GPADAT_OFFSET)
#define GPAPUD      (ELFIN_GPIO_BASE+GPAPUD_OFFSET)
#define GPACONSLP   (ELFIN_GPIO_BASE+GPACONSLP_OFFSET)
#define GPAPUDSLP   (ELFIN_GPIO_BASE+GPAPUDSLP_OFFSET)
#define GPBCON      (ELFIN_GPIO_BASE+GPBCON_OFFSET)
#define GPBDAT      (ELFIN_GPIO_BASE+GPBDAT_OFFSET)
#define GPBPUD      (ELFIN_GPIO_BASE+GPBPUD_OFFSET)
#define GPBCONSLP   (ELFIN_GPIO_BASE+GPBCONSLP_OFFSET)
#define GPBPUDSLP   (ELFIN_GPIO_BASE+GPBPUDSLP_OFFSET)
#define GPCCON      (ELFIN_GPIO_BASE+GPCCON_OFFSET)
#define GPCDAT      (ELFIN_GPIO_BASE+GPCDAT_OFFSET)
#define GPCPUD      (ELFIN_GPIO_BASE+GPCPUD_OFFSET)
#define GPCCONSLP   (ELFIN_GPIO_BASE+GPCCONSLP_OFFSET)
#define GPCPUDSLP   (ELFIN_GPIO_BASE+GPCPUDSLP_OFFSET)
#define GPDCON      (ELFIN_GPIO_BASE+GPDCON_OFFSET)
#define GPDDAT      (ELFIN_GPIO_BASE+GPDDAT_OFFSET)
#define GPDPUD      (ELFIN_GPIO_BASE+GPDPUD_OFFSET)
#define GPDCONSLP   (ELFIN_GPIO_BASE+GPDCONSLP_OFFSET)
#define GPDPUDSLP   (ELFIN_GPIO_BASE+GPDPUDSLP_OFFSET)
#define GPECON      (ELFIN_GPIO_BASE+GPECON_OFFSET)
#define GPEDAT      (ELFIN_GPIO_BASE+GPEDAT_OFFSET)
#define GPEPUD      (ELFIN_GPIO_BASE+GPEPUD_OFFSET)
#define GPECONSLP   (ELFIN_GPIO_BASE+GPECONSLP_OFFSET)
#define GPEPUDSLP   (ELFIN_GPIO_BASE+GPEPUDSLP_OFFSET)
#define GPFCON      (ELFIN_GPIO_BASE+GPFCON_OFFSET)
#define GPFDAT      (ELFIN_GPIO_BASE+GPFDAT_OFFSET)
#define GPFPUD      (ELFIN_GPIO_BASE+GPFPUD_OFFSET)
#define GPFCONSLP   (ELFIN_GPIO_BASE+GPFCONSLP_OFFSET)
#define GPFPUDSLP   (ELFIN_GPIO_BASE+GPFPUDSLP_OFFSET)
#define GPGCON      (ELFIN_GPIO_BASE+GPGCON_OFFSET)
#define GPGDAT      (ELFIN_GPIO_BASE+GPGDAT_OFFSET)
#define GPGPUD      (ELFIN_GPIO_BASE+GPGPUD_OFFSET)
#define GPGCONSLP   (ELFIN_GPIO_BASE+GPGCONSLP_OFFSET)
#define GPGPUDSLP   (ELFIN_GPIO_BASE+GPGPUDSLP_OFFSET)
#define GPHCON0     (ELFIN_GPIO_BASE+GPHCON0_OFFSET)
#define GPHCON1     (ELFIN_GPIO_BASE+GPHCON1_OFFSET)
#define GPHDAT      (ELFIN_GPIO_BASE+GPHDAT_OFFSET)
#define GPHPUD      (ELFIN_GPIO_BASE+GPHPUD_OFFSET)
#define GPHCONSLP   (ELFIN_GPIO_BASE+GPHCONSLP_OFFSET)
#define GPHPUDSLP   (ELFIN_GPIO_BASE+GPHPUDSLP_OFFSET)
#define GPICON      (ELFIN_GPIO_BASE+GPICON_OFFSET)
#define GPIDAT      (ELFIN_GPIO_BASE+GPIDAT_OFFSET)
#define GPIPUD      (ELFIN_GPIO_BASE+GPIPUD_OFFSET)
#define GPICONSLP   (ELFIN_GPIO_BASE+GPICONSLP_OFFSET)
#define GPIPUDSLP   (ELFIN_GPIO_BASE+GPIPUDSLP_OFFSET)
#define GPJCON      (ELFIN_GPIO_BASE+GPJCON_OFFSET)
#define GPJDAT      (ELFIN_GPIO_BASE+GPJDAT_OFFSET)
#define GPJPUD      (ELFIN_GPIO_BASE+GPJPUD_OFFSET)
#define GPJCONSLP   (ELFIN_GPIO_BASE+GPJCONSLP_OFFSET)
#define GPJPUDSLP   (ELFIN_GPIO_BASE+GPJPUDSLP_OFFSET)
#define GPKCON0     (ELFIN_GPIO_BASE+GPKCON0_OFFSET)
#define GPKCON1     (ELFIN_GPIO_BASE+GPKCON1_OFFSET)
#define GPKDAT      (ELFIN_GPIO_BASE+GPKDAT_OFFSET)
#define GPKPUD      (ELFIN_GPIO_BASE+GPKPUD_OFFSET)
#define GPLCON0     (ELFIN_GPIO_BASE+GPLCON0_OFFSET)
#define GPLCON1     (ELFIN_GPIO_BASE+GPLCON1_OFFSET)
#define GPLDAT      (ELFIN_GPIO_BASE+GPLDAT_OFFSET)
#define GPLPUD      (ELFIN_GPIO_BASE+GPLPUD_OFFSET)
#define GPMCON      (ELFIN_GPIO_BASE+GPMCON_OFFSET)
#define GPMDAT      (ELFIN_GPIO_BASE+GPMDAT_OFFSET)
#define GPMPUD      (ELFIN_GPIO_BASE+GPMPUD_OFFSET)
#define GPNCON      (ELFIN_GPIO_BASE+GPNCON_OFFSET)
#define GPNDAT      (ELFIN_GPIO_BASE+GPNDAT_OFFSET)
#define GPNPUD      (ELFIN_GPIO_BASE+GPNPUD_OFFSET)
#define GPOCON      (ELFIN_GPIO_BASE+GPOCON_OFFSET)
#define GPODAT      (ELFIN_GPIO_BASE+GPODAT_OFFSET)
#define GPOPUD      (ELFIN_GPIO_BASE+GPOPUD_OFFSET)
#define GPOCONSLP   (ELFIN_GPIO_BASE+GPOCONSLP_OFFSET)
#define GPOPUDSLP   (ELFIN_GPIO_BASE+GPOPUDSLP_OFFSET)
#define GPPCON      (ELFIN_GPIO_BASE+GPPCON_OFFSET)
#define GPPDAT      (ELFIN_GPIO_BASE+GPPDAT_OFFSET)
#define GPPPUD      (ELFIN_GPIO_BASE+GPPPUD_OFFSET)
#define GPPCONSLP   (ELFIN_GPIO_BASE+GPPCONSLP_OFFSET)
#define GPPPUDSLP   (ELFIN_GPIO_BASE+GPPPUDSLP_OFFSET)
#define GPQCON      (ELFIN_GPIO_BASE+GPQCON_OFFSET)
#define GPQDAT      (ELFIN_GPIO_BASE+GPQDAT_OFFSET)
#define GPQPUD      (ELFIN_GPIO_BASE+GPQPUD_OFFSET)
#define GPQCONSLP   (ELFIN_GPIO_BASE+GPQCONSLP_OFFSET)
#define GPQPUDSLP   (ELFIN_GPIO_BASE+GPQPUDSLP_OFFSET)

#ifndef __ASSEMBLY__
static inline S3C64XX_GPIO * S3C64XX_GetBase_GPIO(void)
{
    return (S3C64XX_GPIO *)ELFIN_GPIO_BASE;
}

#endif /* __ASSEMBLY__ */


/* Base addresses for each of the banks */

#define S3C64XX_GPIOREG(reg)	(ELFIN_GPIO_BASE + (reg))

#define S3C64XX_GPA_BASE	S3C64XX_GPIOREG(0x0000)
#define S3C64XX_GPB_BASE	S3C64XX_GPIOREG(0x0020)
#define S3C64XX_GPC_BASE	S3C64XX_GPIOREG(0x0040)
#define S3C64XX_GPD_BASE	S3C64XX_GPIOREG(0x0060)
#define S3C64XX_GPE_BASE	S3C64XX_GPIOREG(0x0080)
#define S3C64XX_GPF_BASE	S3C64XX_GPIOREG(0x00A0)
#define S3C64XX_GPG_BASE	S3C64XX_GPIOREG(0x00C0)
#define S3C64XX_GPH_BASE	S3C64XX_GPIOREG(0x00E0)
#define S3C64XX_GPI_BASE	S3C64XX_GPIOREG(0x0100)
#define S3C64XX_GPJ_BASE	S3C64XX_GPIOREG(0x0120)
#define S3C64XX_GPK_BASE	S3C64XX_GPIOREG(0x0800)
#define S3C64XX_GPL_BASE	S3C64XX_GPIOREG(0x0810)
#define S3C64XX_GPM_BASE	S3C64XX_GPIOREG(0x0820)
#define S3C64XX_GPN_BASE	S3C64XX_GPIOREG(0x0830)
#define S3C64XX_GPO_BASE	S3C64XX_GPIOREG(0x0140)
#define S3C64XX_GPP_BASE	S3C64XX_GPIOREG(0x0160)
#define S3C64XX_GPQ_BASE	S3C64XX_GPIOREG(0x0180)

/* SPCON */

#define S3C64XX_SPCON		S3C64XX_GPIOREG(0x1A0)

#define S3C64XX_SPCON_DRVCON_CAM_MASK		(0x3 << 30)
#define S3C64XX_SPCON_DRVCON_CAM_SHIFT		(30)
#define S3C64XX_SPCON_DRVCON_CAM_2mA		(0x0 << 30)
#define S3C64XX_SPCON_DRVCON_CAM_4mA		(0x1 << 30)
#define S3C64XX_SPCON_DRVCON_CAM_7mA		(0x2 << 30)
#define S3C64XX_SPCON_DRVCON_CAM_9mA		(0x3 << 30)

#define S3C64XX_SPCON_DRVCON_HSSPI_MASK		(0x3 << 28)
#define S3C64XX_SPCON_DRVCON_HSSPI_SHIFT	(28)
#define S3C64XX_SPCON_DRVCON_HSSPI_2mA		(0x0 << 28)
#define S3C64XX_SPCON_DRVCON_HSSPI_4mA		(0x1 << 28)
#define S3C64XX_SPCON_DRVCON_HSSPI_7mA		(0x2 << 28)
#define S3C64XX_SPCON_DRVCON_HSSPI_9mA		(0x3 << 28)

#define S3C64XX_SPCON_DRVCON_HSMMC_MASK		(0x3 << 26)
#define S3C64XX_SPCON_DRVCON_HSMMC_SHIFT	(26)
#define S3C64XX_SPCON_DRVCON_HSMMC_2mA		(0x0 << 26)
#define S3C64XX_SPCON_DRVCON_HSMMC_4mA		(0x1 << 26)
#define S3C64XX_SPCON_DRVCON_HSMMC_7mA		(0x2 << 26)
#define S3C64XX_SPCON_DRVCON_HSMMC_9mA		(0x3 << 26)

#define S3C64XX_SPCON_DRVCON_LCD_MASK		(0x3 << 24)
#define S3C64XX_SPCON_DRVCON_LCD_SHIFT		(24)
#define S3C64XX_SPCON_DRVCON_LCD_2mA		(0x0 << 24)
#define S3C64XX_SPCON_DRVCON_LCD_4mA		(0x1 << 24)
#define S3C64XX_SPCON_DRVCON_LCD_7mA		(0x2 << 24)
#define S3C64XX_SPCON_DRVCON_LCD_9mA		(0x3 << 24)

#define S3C64XX_SPCON_DRVCON_MODEM_MASK		(0x3 << 22)
#define S3C64XX_SPCON_DRVCON_MODEM_SHIFT	(22)
#define S3C64XX_SPCON_DRVCON_MODEM_2mA		(0x0 << 22)
#define S3C64XX_SPCON_DRVCON_MODEM_4mA		(0x1 << 22)
#define S3C64XX_SPCON_DRVCON_MODEM_7mA		(0x2 << 22)
#define S3C64XX_SPCON_DRVCON_MODEM_9mA		(0x3 << 22)

#define S3C64XX_SPCON_nRSTOUT_OEN		(1 << 21)

#define S3C64XX_SPCON_DRVCON_SPICLK1_MASK	(0x3 << 18)
#define S3C64XX_SPCON_DRVCON_SPICLK1_SHIFT	(18)
#define S3C64XX_SPCON_DRVCON_SPICLK1_2mA	(0x0 << 18)
#define S3C64XX_SPCON_DRVCON_SPICLK1_4mA	(0x1 << 18)
#define S3C64XX_SPCON_DRVCON_SPICLK1_7mA	(0x2 << 18)
#define S3C64XX_SPCON_DRVCON_SPICLK1_9mA	(0x3 << 18)

#define S3C64XX_SPCON_MEM1_DQS_PUD_MASK		(0x3 << 16)
#define S3C64XX_SPCON_MEM1_DQS_PUD_SHIFT	(16)
#define S3C64XX_SPCON_MEM1_DQS_PUD_DISABLED	(0x0 << 16)
#define S3C64XX_SPCON_MEM1_DQS_PUD_DOWN		(0x1 << 16)
#define S3C64XX_SPCON_MEM1_DQS_PUD_UP		(0x2 << 16)

#define S3C64XX_SPCON_MEM1_D_PUD1_MASK		(0x3 << 14)
#define S3C64XX_SPCON_MEM1_D_PUD1_SHIFT		(14)
#define S3C64XX_SPCON_MEM1_D_PUD1_DISABLED	(0x0 << 14)
#define S3C64XX_SPCON_MEM1_D_PUD1_DOWN		(0x1 << 14)
#define S3C64XX_SPCON_MEM1_D_PUD1_UP		(0x2 << 14)

#define S3C64XX_SPCON_MEM1_D_PUD0_MASK		(0x3 << 12)
#define S3C64XX_SPCON_MEM1_D_PUD0_SHIFT		(12)
#define S3C64XX_SPCON_MEM1_D_PUD0_DISABLED	(0x0 << 12)
#define S3C64XX_SPCON_MEM1_D_PUD0_DOWN		(0x1 << 12)
#define S3C64XX_SPCON_MEM1_D_PUD0_UP		(0x2 << 12)

#define S3C64XX_SPCON_MEM0_D_PUD_MASK		(0x3 << 8)
#define S3C64XX_SPCON_MEM0_D_PUD_SHIFT		(8)
#define S3C64XX_SPCON_MEM0_D_PUD_DISABLED	(0x0 << 8)
#define S3C64XX_SPCON_MEM0_D_PUD_DOWN		(0x1 << 8)
#define S3C64XX_SPCON_MEM0_D_PUD_UP		(0x2 << 8)

#define S3C64XX_SPCON_USBH_DMPD			(1 << 7)
#define S3C64XX_SPCON_USBH_DPPD			(1 << 6)
#define S3C64XX_SPCON_USBH_PUSW2		(1 << 5)
#define S3C64XX_SPCON_USBH_PUSW1		(1 << 4)
#define S3C64XX_SPCON_USBH_SUSPND		(1 << 3)

#define S3C64XX_SPCON_LCD_SEL_MASK		(0x3 << 0)
#define S3C64XX_SPCON_LCD_SEL_SHIFT		(0)
#define S3C64XX_SPCON_LCD_SEL_HOST		(0x0 << 0)
#define S3C64XX_SPCON_LCD_SEL_RGB		(0x1 << 0)
#define S3C64XX_SPCON_LCD_SEL_606_656		(0x2 << 0)


/* External interrupt registers */

#define S3C64XX_EINT12CON	S3C64XX_GPIOREG(0x200)
#define S3C64XX_EINT34CON	S3C64XX_GPIOREG(0x204)
#define S3C64XX_EINT56CON	S3C64XX_GPIOREG(0x208)
#define S3C64XX_EINT78CON	S3C64XX_GPIOREG(0x20C)
#define S3C64XX_EINT9CON	S3C64XX_GPIOREG(0x210)

#define S3C64XX_EINT12FLTCON	S3C64XX_GPIOREG(0x220)
#define S3C64XX_EINT34FLTCON	S3C64XX_GPIOREG(0x224)
#define S3C64XX_EINT56FLTCON	S3C64XX_GPIOREG(0x228)
#define S3C64XX_EINT78FLTCON	S3C64XX_GPIOREG(0x22C)
#define S3C64XX_EINT9FLTCON	S3C64XX_GPIOREG(0x230)

#define S3C64XX_EINT12MASK	S3C64XX_GPIOREG(0x240)
#define S3C64XX_EINT34MASK	S3C64XX_GPIOREG(0x244)
#define S3C64XX_EINT56MASK	S3C64XX_GPIOREG(0x248)
#define S3C64XX_EINT78MASK	S3C64XX_GPIOREG(0x24C)
#define S3C64XX_EINT9MASK	S3C64XX_GPIOREG(0x250)

#define S3C64XX_EINT12PEND	S3C64XX_GPIOREG(0x260)
#define S3C64XX_EINT34PEND	S3C64XX_GPIOREG(0x264)
#define S3C64XX_EINT56PEND	S3C64XX_GPIOREG(0x268)
#define S3C64XX_EINT78PEND	S3C64XX_GPIOREG(0x26C)
#define S3C64XX_EINT9PEND	S3C64XX_GPIOREG(0x270)

#define S3C64XX_PRIORITY	S3C64XX_GPIOREG(0x280)
#define S3C64XX_PRIORITY_ARB(x)	(1 << (x))

#define S3C64XX_SERVICE		S3C64XX_GPIOREG(0x284)
#define S3C64XX_SERVICEPEND	S3C64XX_GPIOREG(0x288)

#define S3C64XX_EINT0CON0	S3C64XX_GPIOREG(0x900)
#define S3C64XX_EINT0CON1	S3C64XX_GPIOREG(0x904)
#define S3C64XX_EINT0FLTCON0	S3C64XX_GPIOREG(0x910)
#define S3C64XX_EINT0FLTCON1	S3C64XX_GPIOREG(0x914)
#define S3C64XX_EINT0FLTCON2	S3C64XX_GPIOREG(0x918)
#define S3C64XX_EINT0FLTCON3	S3C64XX_GPIOREG(0x91C)

#define S3C64XX_EINT0MASK	S3C64XX_GPIOREG(0x920)
#define S3C64XX_EINT0PEND	S3C64XX_GPIOREG(0x924)

/* GPIO sleep configuration */

#define S3C64XX_SPCONSLP	S3C64XX_GPIOREG(0x880)

#define S3C64XX_SPCONSLP_TDO_PULLDOWN	(1 << 14)
#define S3C64XX_SPCONSLP_CKE1INIT	(1 << 5)

#define S3C64XX_SPCONSLP_RSTOUT_MASK	(0x3 << 12)
#define S3C64XX_SPCONSLP_RSTOUT_OUT0	(0x0 << 12)
#define S3C64XX_SPCONSLP_RSTOUT_OUT1	(0x1 << 12)
#define S3C64XX_SPCONSLP_RSTOUT_HIZ	(0x2 << 12)

#define S3C64XX_SPCONSLP_KPCOL_MASK	(0x3 << 0)
#define S3C64XX_SPCONSLP_KPCOL_OUT0	(0x0 << 0)
#define S3C64XX_SPCONSLP_KPCOL_OUT1	(0x1 << 0)
#define S3C64XX_SPCONSLP_KPCOL_INP	(0x2 << 0)


#define S3C64XX_SLPEN		S3C64XX_GPIOREG(0x930)

#define S3C64XX_SLPEN_USE_xSLP		(1 << 0)
#define S3C64XX_SLPEN_CFG_BYSLPEN	(1 << 1)

#endif /* __S3C64XX_GPIO_REGS_H__ */
